import { NextResponse } from "next/server";

// /api/classes/addclass
export async function POST(req) {
  try {
    const body = await req.json();
    const {
      class_name,
      class_level,
      staff_id,
      room_number,
      capacity,
      user_id,
    } = body;

    // Basic validation (you should add more robust checks in a real app)
    if (!class_name || !class_level || !staff_id) {
      return NextResponse.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Simulate checking for existing class (replace with actual logic later)
    const classNameExists = class_name.toLowerCase() === "existing class"; // Example
    if (classNameExists) {
      return NextResponse.json(
        { error: "Class name already exists. Try adding another class." },
        { status: 409 } // Conflict
      );
    }

    // Simulate successful database insertion and notification
    console.log("Simulating adding new class:", body); // Log the received data

    // Simulate a new class ID being generated by the database
    const newClassId = Math.floor(Math.random() * 1000) + 1;

    return NextResponse.json(
      {
        message: `${class_name} added successfully`,
        id: newClassId,
      },
      { status: 201 } // Created
    );
  } catch (error) {
    console.error("Error simulating add class:", error);
    return NextResponse.json(
      { error: error.message || "Internal Server Error" },
      { status: 500 }
    );
  }
}
