import { NextResponse } from "next/server";

// /api/finance/semfinamanagement/[semester_id]
export async function GET(req, { params }) {
  try {
    const { semester_id } = params;
    if (!semester_id) {
      return NextResponse.json(
        { error: "Semester ID is required" },
        { status: 400 }
      );
    }

    // Mock Data - Replace with your actual mock data
    const mockData = {
      stats: {
        totalRevenue: 3300,
        tuitionRevenue: 3277,
        feedingRevenue: 23,
        feedingOnlyRevenue: 15,
        transportRevenue: 8,
        outstandingPayments: 2651.5,
        recentPayments: 23,
        averagePaymentTime: 0,
        totalExpenses: 1590,
      },
      dailyRevenue: {
        tuitionRevenue: 0,
        feedingRevenue: 0,
        transportRevenue: 0,
        totalDailyRevenue: 0,
      },
      weeklyReportData: [
        {
          date: "2024-08-19",
          tuitionRevenue: 58,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 58,
          expenses: 0,
          profit: 58,
        },
        {
          date: "2024-08-26",
          tuitionRevenue: 0,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 0,
          expenses: 120,
          profit: -120,
        },
        {
          date: "2024-09-16",
          tuitionRevenue: 1750,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 1750,
          expenses: 1160,
          profit: 590,
        },
        {
          date: "2024-10-07",
          tuitionRevenue: 1369,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 1369,
          expenses: 20,
          profit: 1349,
        },
        {
          date: "2024-10-21",
          tuitionRevenue: 0,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 0,
          expenses: 240,
          profit: -240,
        },
        {
          date: "2024-11-04",
          tuitionRevenue: 100,
          feedingRevenue: 15,
          transportRevenue: 8,
          totalRevenue: 123,
          expenses: 50,
          profit: 73,
        },
      ],
      monthlyReportData: [
        {
          date: "2024-08-01",
          tuitionRevenue: 58,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 58,
          expenses: 120,
          profit: -62,
        },
        {
          date: "2024-09-01",
          tuitionRevenue: 1750,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 1750,
          expenses: 1160,
          profit: 590,
        },
        {
          date: "2024-10-01",
          tuitionRevenue: 1369,
          feedingRevenue: 0,
          transportRevenue: 0,
          totalRevenue: 1369,
          expenses: 260,
          profit: 1109,
        },
        {
          date: "2024-11-01",
          tuitionRevenue: 100,
          feedingRevenue: 15,
          transportRevenue: 8,
          totalRevenue: 123,
          expenses: 50,
          profit: 73,
        },
      ],
      semExpensesData: [
        {
          name: "Utilities",
          value: 60,
        },
        {
          name: "Maintenance",
          value: 30,
        },
        {
          name: "Salaries",
          value: 8,
        },
        {
          name: "Supplies",
          value: 3,
        },
      ],
      recentPaymentsForCurrentSem: [
        {
          id: 2,
          student_name: "Emmanuel  Foli",
          amount: "8.00",
          payment_type: "Feeding & Transport",
          old_balance: null,
          new_balance: null,
          date: "2024-11-10",
        },
        {
          id: 1,
          student_name: "Richmond Adasu ",
          amount: "15.00",
          payment_type: "Feeding & Transport",
          old_balance: null,
          new_balance: null,
          date: "2024-11-10",
        },
        {
          id: 31,
          student_name: "Patience  Enyaah ",
          amount: "100.00",
          payment_type: "Tuition",
          old_balance: "0.00",
          new_balance: "-100.00",
          date: "2024-11-06",
        },
        {
          id: 28,
          student_name: "Matilda  Attah ",
          amount: "10.50",
          payment_type: "Tuition",
          old_balance: "897.50",
          new_balance: "887.00",
          date: "2024-10-10",
        },
        {
          id: 30,
          student_name: "Matilda  Attah ",
          amount: "8.50",
          payment_type: "Tuition",
          old_balance: "880.00",
          new_balance: "871.50",
          date: "2024-10-10",
        },
        {
          id: 29,
          student_name: "Matilda  Attah ",
          amount: "7.00",
          payment_type: "Tuition",
          old_balance: "887.00",
          new_balance: "880.00",
          date: "2024-10-10",
        },
        {
          id: 17,
          student_name: "Matilda  Attah ",
          amount: "40.00",
          payment_type: "Tuition",
          old_balance: "1000.00",
          new_balance: "960.00",
          date: "2024-10-09",
        },
        {
          id: 19,
          student_name: "Matilda  Attah ",
          amount: "19.00",
          payment_type: "Tuition",
          old_balance: "927.00",
          new_balance: "908.00",
          date: "2024-10-09",
        },
        {
          id: 20,
          student_name: "Matilda  Attah ",
          amount: "1.00",
          payment_type: "Tuition",
          old_balance: "908.00",
          new_balance: "907.00",
          date: "2024-10-09",
        },
        {
          id: 21,
          student_name: "Matilda  Attah ",
          amount: "2.00",
          payment_type: "Tuition",
          old_balance: "907.00",
          new_balance: "905.00",
          date: "2024-10-09",
        },
        {
          id: 22,
          student_name: "Matilda  Attah ",
          amount: "1.00",
          payment_type: "Tuition",
          old_balance: "905.00",
          new_balance: "904.00",
          date: "2024-10-09",
        },
        {
          id: 23,
          student_name: "Matilda  Attah ",
          amount: "2.00",
          payment_type: "Tuition",
          old_balance: "904.00",
          new_balance: "902.00",
          date: "2024-10-09",
        },
        {
          id: 24,
          student_name: "Matilda  Attah ",
          amount: "1.00",
          payment_type: "Tuition",
          old_balance: "902.00",
          new_balance: "901.00",
          date: "2024-10-09",
        },
        {
          id: 25,
          student_name: "Matilda  Attah ",
          amount: "1.50",
          payment_type: "Tuition",
          old_balance: "901.00",
          new_balance: "899.00",
          date: "2024-10-09",
        },
        {
          id: 27,
          student_name: "Matilda  Attah ",
          amount: "1.50",
          payment_type: "Tuition",
          old_balance: "899.00",
          new_balance: "897.50",
          date: "2024-10-09",
        },
        {
          id: 9,
          student_name: "Matilda  Attah ",
          amount: "300.00",
          payment_type: "Tuition",
          old_balance: "2165.00",
          new_balance: "-1865.00",
          date: "2024-10-09",
        },
        {
          id: 10,
          student_name: "Matilda  Attah ",
          amount: "100.00",
          payment_type: "Tuition",
          old_balance: "1865.00",
          new_balance: "-1765.00",
          date: "2024-10-09",
        },
        {
          id: 11,
          student_name: "Matilda  Attah ",
          amount: "125.00",
          payment_type: "Tuition",
          old_balance: "1765.00",
          new_balance: "-1640.00",
          date: "2024-10-09",
        },
        {
          id: 12,
          student_name: "Matilda  Attah ",
          amount: "150.00",
          payment_type: "Tuition",
          old_balance: "1640.00",
          new_balance: "-1490.00",
          date: "2024-10-09",
        },
        {
          id: 14,
          student_name: "Matilda  Attah ",
          amount: "36.50",
          payment_type: "Tuition",
          old_balance: "1490.00",
          new_balance: null,
          date: "2024-10-09",
        },
        {
          id: 15,
          student_name: "Matilda  Attah ",
          amount: "60.00",
          payment_type: "Tuition",
          old_balance: "1480.00",
          new_balance: "1420.00",
          date: "2024-10-09",
        },
        {
          id: 16,
          student_name: "Matilda  Attah ",
          amount: "420.00",
          payment_type: "Tuition",
          old_balance: "1420.00",
          new_balance: "1000.00",
          date: "2024-10-09",
        },
        {
          id: 18,
          student_name: "Matilda  Attah ",
          amount: "32.50",
          payment_type: "Tuition",
          old_balance: "960.00",
          new_balance: "927.00",
          date: "2024-10-09",
        },
        {
          id: 8,
          student_name: "John Nyarkoh",
          amount: "50.00",
          payment_type: "Tuition",
          old_balance: "50.00",
          new_balance: "0.00",
          date: "2024-10-08",
        },
        {
          id: 7,
          student_name: "John Nyarkoh",
          amount: "850.00",
          payment_type: "Tuition",
          old_balance: "800.00",
          new_balance: "50.00",
          date: "2024-09-17",
        },
        {
          id: 6,
          student_name: "Matilda  Attah ",
          amount: "900.00",
          payment_type: "Tuition",
          old_balance: "700.00",
          new_balance: "200.00",
          date: "2024-09-16",
        },
        {
          id: 5,
          student_name: "nelson1 Dorkordi",
          amount: "-50.00",
          payment_type: "Tuition",
          old_balance: "0.00",
          new_balance: "-50.00",
          date: "2024-08-24",
        },
        {
          id: 2,
          student_name: "nelson1 Dorkordi",
          amount: "50.00",
          payment_type: "Tuition",
          old_balance: "30.00",
          new_balance: "0.00",
          date: "2024-08-23",
        },
        {
          id: 3,
          student_name: "nelson1 Dorkordi",
          amount: "-32.00",
          payment_type: "Tuition",
          old_balance: "0.00",
          new_balance: "32.00",
          date: "2024-08-23",
        },
        {
          id: 4,
          student_name: "nelson1 Dorkordi",
          amount: "40.00",
          payment_type: "Tuition",
          old_balance: "32.00",
          new_balance: "0.00",
          date: "2024-08-23",
        },
        {
          id: 1,
          student_name: "nelson1 Dorkordi",
          amount: "50.00",
          payment_type: "Tuition",
          old_balance: "80.00",
          new_balance: "30.00",
          date: "2024-08-23",
        },
      ],
      semesterExpensesForCurrentSem: [
        {
          id: 9,
          recipient_name: "Master Ebo",
          amount: "50.00",
          expense_category: "Utilities",
          date: "2024-11-07",
        },
        {
          id: 8,
          recipient_name: "Addo d",
          amount: "40.00",
          expense_category: "Maintenance",
          date: "2024-10-26",
        },
        {
          id: 7,
          recipient_name: "mama esther",
          amount: "200.00",
          expense_category: "Utilities",
          date: "2024-10-26",
        },
        {
          id: 6,
          recipient_name: "Master Ebo",
          amount: "20.00",
          expense_category: "Maintenance",
          date: "2024-10-08",
        },
        {
          id: 5,
          recipient_name: "Master Ebo",
          amount: "420.00",
          expense_category: "Maintenance",
          date: "2024-09-20",
        },
        {
          id: 3,
          recipient_name: "CEPME",
          amount: "40.00",
          expense_category: "Supplies",
          date: "2024-09-16",
        },
        {
          id: 4,
          recipient_name: "Amam Cobina",
          amount: "700.00",
          expense_category: "Utilities",
          date: "2024-09-16",
        },
        {
          id: 1,
          recipient_name: "Ernest  Wilson",
          amount: "60.00",
          expense_category: "Salaries",
          date: "2024-08-28",
        },
        {
          id: 2,
          recipient_name: "Ernest  Wilson",
          amount: "60.00",
          expense_category: "Salaries",
          date: "2024-08-28",
        },
      ],
    };


    // Example of how to conditionally populate mockData based on semester_id
    if (semester_id === "1") {
      mockData.stats = {
        totalRevenue: 3300,
        tuitionRevenue: 3277,
        feedingRevenue: 23,
        feedingOnlyRevenue: 15,
        transportRevenue: 8,
        outstandingPayments: 2651.5,
        recentPayments: 23,
        averagePaymentTime: 0,
        totalExpenses: 1590,
      };
      // ... populate other arrays in mockData for semester 1
    } else if (semester_id === "2") {
      //paste data here if semester_id is 2
      mockData.stats = {
        totalRevenue: 3300,
        tuitionRevenue: 3277,
        feedingRevenue: 23,
        feedingOnlyRevenue: 15,
        transportRevenue: 8,
        outstandingPayments: 2651.5,
        recentPayments: 23,
        averagePaymentTime: 0,
        totalExpenses: 1590,
      };
      // ... populate other arrays in mockData for semester 2
    }

    return NextResponse.json(mockData, { status: 200 });
  } catch (error) {
    console.error("Error (simulated):", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
