import { NextResponse } from "next/server";

// /api/staff/all

export async function GET(req) {
  try {
    const { searchParams } = new URL(req.url);
    const query = searchParams.get("query");

    // Mock staff data (you need to expand this with more realistic data)
    const mockStaffData = [
      {
        staff_id: 6,
        user_id: 15,
        first_name: "Ernest ",
        last_name: "Owusu ",
        middle_name: "",
        date_of_birth: "2023-07-30T00:00:00.000Z",
        gender: "M",
        marital_status: "Divorced",
        address: "assemblies of god ghana",
        phone_number: "+233551577446",
        email: "atlcoccus@gmail7885.com",
        emergency_contact: "0502109023",
        date_of_joining: "2024-01-08T00:00:00.000Z",
        designation: "",
        department: "English",
        salary: "806.00",
        account_number: "0702109023",
        contract_type: "Part-time",
        employment_status: "On Leave",
        qualification: "degree",
        experience: "worked with jsx",
        blood_group: "AB-",
        national_id: "50865769",
        passport_number: "20540244",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2FANGEL%20PROJECT%202-01.png2024-09-06T14%3A15%3A53.326Z?alt=media&token=af21a9b5-6f99-4e1b-b39c-d4c8908df40c",
        teaching_subject: "social",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "non teaching",
      },
      {
        staff_id: 13,
        user_id: 22,
        first_name: "Ernest 1",
        last_name: "Nelson ",
        middle_name: "Tawiah",
        date_of_birth: "1996-02-19T00:00:00.000Z",
        gender: "M",
        marital_status: "Single",
        address: "jkhgjgg",
        phone_number: "25844245",
        email: "atlcoccus123@gmail.com25",
        emergency_contact: "0551577446",
        date_of_joining: "2024-08-19T00:00:00.000Z",
        designation: "",
        department: "Music",
        salary: "20.00",
        account_number: "502856",
        contract_type: "Full-time",
        employment_status: "Active",
        qualification: "HND ",
        experience: "5 years",
        blood_group: "AB+",
        national_id: "54246",
        passport_number: "584455",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2Fdownload.jpeg2024-08-19T15%3A32%3A09.961Z?alt=media&token=f9a1c6aa-e655-4460-bd08-cae23bc38c76",
        teaching_subject: "",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "admin",
      },
      {
        staff_id: 3,
        user_id: 12,
        first_name: "John ",
        last_name: "Nyarkoh",
        middle_name: "Akwasikumah",
        date_of_birth: "2024-07-28T00:00:00.000Z",
        gender: "M",
        marital_status: "Single",
        address: "assemblies of god ghana",
        phone_number: "+233551577446",
        email: "atlcoccus@gmail123.com",
        emergency_contact: "0504238397",
        date_of_joining: "2024-08-13T00:00:00.000Z",
        designation: "",
        department: "English",
        salary: "500.00",
        account_number: "0702109023",
        contract_type: "Full-time",
        employment_status: "Active",
        qualification: "degree",
        experience: "worked with js",
        blood_group: "AB+",
        national_id: "50865769",
        passport_number: "20540244",
        photo: null,
        teaching_subject: "English",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "teaching staff",
      },
      {
        staff_id: 2,
        user_id: 9,
        first_name: "Matilda ",
        last_name: "Attah ",
        middle_name: "Emefa",
        date_of_birth: "2024-07-29T00:00:00.000Z",
        gender: "F",
        marital_status: "Single",
        address: "assemblies of god ghana",
        phone_number: "+233551577446",
        email: "atlcoccus@gmail2.com",
        emergency_contact: "0504238397",
        date_of_joining: "2024-08-12T00:00:00.000Z",
        designation: "",
        department: "Mathematics",
        salary: "800.00",
        account_number: "0702109023",
        contract_type: "Full-time",
        employment_status: "Active",
        qualification: "degrees",
        experience: "worked with js",
        blood_group: "AB-",
        national_id: "50865769",
        passport_number: "",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2FIMG-20220401-WA0018.jpg2024-08-12T17%3A26%3A03.675Z?alt=media&token=f97ee86c-f2ef-473b-894f-211235022277",
        teaching_subject: "mathematics",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "teaching staff",
      },
      {
        staff_id: 1,
        user_id: 8,
        first_name: "Nelson",
        last_name: "Dorkordi",
        middle_name: "Tawiah",
        date_of_birth: "2024-07-28T00:00:00.000Z",
        gender: "M",
        marital_status: "Single",
        address: "assemblies of god ghana",
        phone_number: "+233551577446",
        email: "atlcoccus@gmail1.com",
        emergency_contact: "0504238397",
        date_of_joining: "2024-08-12T00:00:00.000Z",
        designation: "",
        department: "Mathematics",
        salary: "400.00",
        account_number: "0702109023",
        contract_type: "Contract",
        employment_status: "Active",
        qualification: "degrees",
        experience: "worked with js",
        blood_group: "A+",
        national_id: "50865769",
        passport_number: "",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2Fphoto_2023-11-02_11-14-45.jpg2024-08-12T17%3A02%3A55.492Z?alt=media&token=0e663bd9-746b-4b01-a98c-665694a8b7bc",
        teaching_subject: "mathematics",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "teaching staff",
      },
      {
        staff_id: 11,
        user_id: 20,
        first_name: "Nelson",
        last_name: "Kweku ",
        middle_name: "Legend",
        date_of_birth: "2024-07-29T00:00:00.000Z",
        gender: "M",
        marital_status: "Married",
        address: "fffjhng\nvcfgfg",
        phone_number: "25844245",
        email: "nelsodork@gmail.com",
        emergency_contact: "0551577446",
        date_of_joining: "2024-07-31T00:00:00.000Z",
        designation: "",
        department: "Music",
        salary: "809.00",
        account_number: "20",
        contract_type: "Full-time",
        employment_status: "On Leave",
        qualification: "HND ",
        experience: "5 years",
        blood_group: "AB+",
        national_id: "54246",
        passport_number: "584455",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2FdorkordiChannel4.jpeg2024-08-16T14%3A04%3A23.167Z?alt=media&token=bb14602c-940b-445b-86d5-bcea27f7b130",
        teaching_subject: "578",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "teaching staff",
      },
      {
        staff_id: 16,
        user_id: 35,
        first_name: "Patience ",
        last_name: "Enyaah",
        middle_name: "Maame Araba",
        date_of_birth: "2004-10-07T00:00:00.000Z",
        gender: "F",
        marital_status: "Married",
        address: "Ghana post gps 2546",
        phone_number: "0547323204",
        email: "enyaahpat1@gmail.com",
        emergency_contact: "0551577446",
        date_of_joining: "2024-10-07T00:00:00.000Z",
        designation: "Staff",
        department: "Music",
        salary: "400.00",
        account_number: "15468753",
        contract_type: "Full-time",
        employment_status: "Active",
        qualification: "Diploma",
        experience: "2",
        blood_group: "A+",
        national_id: "23564789",
        passport_number: "",
        photo: null,
        teaching_subject: "",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "teaching staff",
      },
      {
        staff_id: 15,
        user_id: 26,
        first_name: "admin",
        last_name: "admin",
        middle_name: "admin",
        date_of_birth: "2024-08-20T00:00:00.000Z",
        gender: "M",
        marital_status: "Single",
        address: "admin",
        phone_number: "0551577446",
        email: "admin@admin",
        emergency_contact: "0551577446",
        date_of_joining: "2024-08-20T00:00:00.000Z",
        designation: "Admin",
        department: "admin",
        salary: "50000.00",
        account_number: "8040750",
        contract_type: "Contract",
        employment_status: "Active",
        qualification: "HND ",
        experience: "5 years",
        blood_group: "O+",
        national_id: "54246",
        passport_number: "584455",
        photo:
          "https://firebasestorage.googleapis.com/v0/b/school-management-e22be.appspot.com/o/images%2Fphoto_2023-11-02_11-14-45.jpg2024-08-20T14%3A48%3A00.576Z?alt=media&token=922165c8-4b73-4878-bd36-338f04242ff2",
        teaching_subject: "",
        class_teacher: null,
        subject_in_charge: null,
        house_in_charge: null,
        bus_in_charge: null,
        library_in_charge: null,
        status: "active",
        role: "admin",
      },
    ];


    let filteredStaff = mockStaffData;

    if (query) {
      // Simulate search
      const lowerCaseQuery = query.toLowerCase();
      filteredStaff = mockStaffData.filter(
        (staff) =>
          staff.first_name.toLowerCase().includes(lowerCaseQuery) ||
          staff.last_name.toLowerCase().includes(lowerCaseQuery) ||
          (staff.email && staff.email.toLowerCase().includes(lowerCaseQuery)) ||
          staff.role.toLowerCase().includes(lowerCaseQuery)
        //(staff.employee_id && staff.employee_id.toLowerCase().includes(lowerCaseQuery)) // Assuming you have employee_id in your mock data
      );
    }

    // Simulate ordering (add more sort conditions as needed)
    filteredStaff.sort((a, b) => {
      const nameA = a.first_name.toLowerCase();
      const nameB = b.first_name.toLowerCase();
      if (nameA < nameB) return -1;
      if (nameA > nameB) return 1;
      return 0;
    });

    return NextResponse.json(filteredStaff, { status: 200 });
  } catch (error) {
    console.error("Mock API error:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
