import { NextResponse } from "next/server";

// /api/attendance/getattendancereport/[class_id]/[semester_id]/route.js
export async function GET(req, { params }) {
  try {
    // Generate dummy data
    const dummyData = {
      classStatistics: {
        totalStudents: 35,
        totalDays: 180, // Example: 20 days per student x 35 students, adjust as needed
        totalPresent: 480,
        totalAbsent: 65,
        totalLate: 25,
        averageAttendanceRate: 85,
      },
      students: [
        {
          id: 1,
          name: "Alice Smith",
          studentId: 101,
          present: 16,
          absent: 2,
          late: 2,
          attendanceRate: 90,
        },
        {
          id: 2,
          name: "Bob Johnson",
          studentId: 102,
          present: 14,
          absent: 4,
          late: 0,
          attendanceRate: 78,
        },
        {
          id: 3,
          name: "Charlie Brown",
          studentId: 103,
          present: 18,
          absent: 1,
          late: 1,
          attendanceRate: 95,
        },
        // ... add more students (up to 35 for this example) ...
        {
          id: 4,
          name: "Diana Lee",
          studentId: 104,
          present: 15,
          absent: 3,
          late: 2,
          attendanceRate: 85,
        },
        {
          id: 5,
          name: "Ethan Kim",
          studentId: 105,
          present: 17,
          absent: 2,
          late: 1,
          attendanceRate: 90,
        },
        {
          id: 6,
          name: "Fiona Chen",
          studentId: 106,
          present: 13,
          absent: 5,
          late: 2,
          attendanceRate: 75,
        },
        {
          id: 7,
          name: "George Davis",
          studentId: 107,
          present: 16,
          absent: 3,
          late: 1,
          attendanceRate: 85,
        },
        {
          id: 8,
          name: "Hannah Wilson",
          studentId: 108,
          present: 12,
          absent: 6,
          late: 2,
          attendanceRate: 70,
        },
        {
          id: 9,
          name: "Ian Rodriguez",
          studentId: 109,
          present: 18,
          absent: 2,
          late: 0,
          attendanceRate: 90,
        },
        {
          id: 10,
          name: "Julia Martinez",
          studentId: 110,
          present: 15,
          absent: 4,
          late: 1,
          attendanceRate: 80,
        },
        {
          id: 11,
          name: "Kevin Taylor",
          studentId: 111,
          present: 14,
          absent: 3,
          late: 3,
          attendanceRate: 80,
        },
        {
          id: 12,
          name: "Linda Thomas",
          studentId: 112,
          present: 17,
          absent: 1,
          late: 2,
          attendanceRate: 95,
        },
        {
          id: 13,
          name: "Michael Jackson",
          studentId: 113,
          present: 16,
          absent: 2,
          late: 2,
          attendanceRate: 90,
        },
        {
          id: 14,
          name: "Nancy Anderson",
          studentId: 114,
          present: 13,
          absent: 4,
          late: 3,
          attendanceRate: 80,
        },
        {
          id: 15,
          name: "Oliver White",
          studentId: 115,
          present: 18,
          absent: 2,
          late: 0,
          attendanceRate: 90,
        },
        {
          id: 16,
          name: "Patricia Harris",
          studentId: 116,
          present: 15,
          absent: 3,
          late: 2,
          attendanceRate: 85,
        },
        {
          id: 17,
          name: "Quentin Lewis",
          studentId: 117,
          present: 14,
          absent: 4,
          late: 2,
          attendanceRate: 80,
        },
        {
          id: 18,
          name: "Rachel Walker",
          studentId: 118,
          present: 17,
          absent: 2,
          late: 1,
          attendanceRate: 90,
        },
        {
          id: 19,
          name: "Samuel Hall",
          studentId: 119,
          present: 16,
          absent: 3,
          late: 1,
          attendanceRate: 85,
        },
        {
          id: 20,
          name: "Tina Young",
          studentId: 120,
          present: 12,
          absent: 5,
          late: 3,
          attendanceRate: 75,
        },
        {
          id: 21,
          name: "Ulysses King",
          studentId: 121,
          present: 18,
          absent: 1,
          late: 1,
          attendanceRate: 95,
        },
        {
          id: 22,
          name: "Victoria Wright",
          studentId: 122,
          present: 15,
          absent: 4,
          late: 1,
          attendanceRate: 80,
        },
        {
          id: 23,
          name: "William Lopez",
          studentId: 123,
          present: 14,
          absent: 2,
          late: 4,
          attendanceRate: 90,
        },
        {
          id: 24,
          name: "Xavier Hill",
          studentId: 124,
          present: 17,
          absent: 2,
          late: 1,
          attendanceRate: 90,
        },
        {
          id: 25,
          name: "Yasmine Scott",
          studentId: 125,
          present: 16,
          absent: 3,
          late: 1,
          attendanceRate: 85,
        },
        {
          id: 26,
          name: "Zachary Green",
          studentId: 126,
          present: 13,
          absent: 4,
          late: 3,
          attendanceRate: 80,
        },
        {
          id: 27,
          name: "Abigail Adams",
          studentId: 127,
          present: 18,
          absent: 2,
          late: 0,
          attendanceRate: 90,
        },
        {
          id: 28,
          name: "Benjamin Baker",
          studentId: 128,
          present: 15,
          absent: 3,
          late: 2,
          attendanceRate: 85,
        },
        {
          id: 29,
          name: "Catherine Clark",
          studentId: 129,
          present: 14,
          absent: 4,
          late: 2,
          attendanceRate: 80,
        },
        {
          id: 30,
          name: "Daniel Garcia",
          studentId: 130,
          present: 17,
          absent: 2,
          late: 1,
          attendanceRate: 90,
        },
        {
          id: 31,
          name: "Emma Miller",
          studentId: 131,
          present: 16,
          absent: 3,
          late: 1,
          attendanceRate: 85,
        },
        {
          id: 32,
          name: "Felix Moore",
          studentId: 132,
          present: 13,
          absent: 5,
          late: 2,
          attendanceRate: 75,
        },
        {
          id: 33,
          name: "Gina Nelson",
          studentId: 133,
          present: 18,
          absent: 2,
          late: 0,
          attendanceRate: 90,
        },
        {
          id: 34,
          name: "Henry Perez",
          studentId: 134,
          present: 15,
          absent: 4,
          late: 1,
          attendanceRate: 80,
        },
        {
          id: 35,
          name: "Isabella Roberts",
          studentId: 135,
          present: 14,
          absent: 3,
          late: 3,
          attendanceRate: 80,
        },
      ],
      semesterDates: {
        start_date: "2024-08-01T00:00:00.000Z",
        end_date: "2024-12-15T00:00:00.000Z",
      },
    };

    return NextResponse.json(dummyData, { status: 200 });
  } catch (error) {
    console.error("Error generating dummy data:", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}
