import { NextResponse } from "next/server";

// /api/fees/getpaymenthistory

export async function GET(req) {
  try {
    const { searchParams } = new URL(req.url);
    const query = searchParams.get("query");
    console.log("query", query);

    let mockData;

    if (query) {
      // Mock data for search (filter based on query)
      const lowerQuery = query.toLowerCase();
      mockData = [
        {
          collection_id: 32,
          student_id: 5,
          payment_date: "2024-11-18",
          amount_received: "250.00",
          old_balance: "600.00",
          new_balance: "350.00",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-11-18T20:36:25.911Z",
          received_by: 26,
          comment: null,
          student_name: "Richmond Adasu ",
          staff_name: "admin admin",
          class_name: "Class 3",
        },
        {
          collection_id: 31,
          student_id: 4,
          payment_date: "2024-11-06",
          amount_received: "100.00",
          old_balance: "0.00",
          new_balance: "-100.00",
          fee_type: null,
          payment_mode: "Momo",
          status: "active",
          created_at: "2024-11-06T15:14:58.426Z",
          received_by: 26,
          comment: null,
          student_name: "Patience  Enyaah ",
          staff_name: "admin admin",
          class_name: "Completed",
        },
        {
          collection_id: 30,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "8.50",
          old_balance: "880.00",
          new_balance: "871.50",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-10-10T02:50:52.786Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 29,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "7.00",
          old_balance: "887.00",
          new_balance: "880.00",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-10-10T02:49:04.670Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 28,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "10.50",
          old_balance: "897.50",
          new_balance: "887.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-10T00:14:37.436Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 27,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.50",
          old_balance: "899.00",
          new_balance: "897.50",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:55:56.647Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 25,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.50",
          old_balance: "901.00",
          new_balance: "899.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:25:14.010Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 24,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "902.00",
          new_balance: "901.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:15:29.191Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 23,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "2.00",
          old_balance: "904.00",
          new_balance: "902.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:13:31.926Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 22,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "905.00",
          new_balance: "904.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:25:12.925Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 21,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "2.00",
          old_balance: "907.00",
          new_balance: "905.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:21:34.792Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 20,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "908.00",
          new_balance: "907.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:11:55.743Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 19,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "19.00",
          old_balance: "927.00",
          new_balance: "908.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:08:53.451Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 18,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "32.50",
          old_balance: "960.00",
          new_balance: "927.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:06:16.128Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 17,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "40.00",
          old_balance: "1000.00",
          new_balance: "960.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T20:53:45.942Z",
          received_by: 26,
          comment: "this is the best comment yet",
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 16,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "420.00",
          old_balance: "1420.00",
          new_balance: "1000.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T20:06:12.977Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 15,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "60.00",
          old_balance: "1480.00",
          new_balance: "1420.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:36:41.679Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 14,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "36.50",
          old_balance: "1490.00",
          new_balance: null,
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:24:16.790Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 12,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "150.00",
          old_balance: "1640.00",
          new_balance: "-1490.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:05:52.823Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 11,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "125.00",
          old_balance: "1765.00",
          new_balance: "-1640.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T17:26:26.859Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 10,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "100.00",
          old_balance: "1865.00",
          new_balance: "-1765.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T08:28:31.167Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 9,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "300.00",
          old_balance: "2165.00",
          new_balance: "-1865.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T00:32:16.913Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 8,
          student_id: 2,
          payment_date: "2024-10-08",
          amount_received: "50.00",
          old_balance: "50.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-08T22:29:03.668Z",
          received_by: 26,
          comment: null,
          student_name: "John Nyarkoh",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 7,
          student_id: 2,
          payment_date: "2024-09-17",
          amount_received: "850.00",
          old_balance: "800.00",
          new_balance: "50.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-09-17T05:46:15.338Z",
          received_by: 26,
          comment: "not needed",
          student_name: "John Nyarkoh",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 6,
          student_id: 3,
          payment_date: "2024-09-16",
          amount_received: "900.00",
          old_balance: "700.00",
          new_balance: "200.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-09-16T21:37:42.335Z",
          received_by: 26,
          comment: "not a sensible comment",
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 5,
          student_id: 1,
          payment_date: "2024-08-24",
          amount_received: "-50.00",
          old_balance: "0.00",
          new_balance: "-50.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-24T00:02:45.215Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 4,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "40.00",
          old_balance: "32.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:59:51.816Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 3,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "-32.00",
          old_balance: "0.00",
          new_balance: "32.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:56:33.864Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 2,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "50.00",
          old_balance: "30.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:48:53.982Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 1,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "50.00",
          old_balance: "80.00",
          new_balance: "30.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T22:52:06.443Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
      ].filter((payment) => {
        const studentName = payment.student_name.toLowerCase();
        const className = payment.class_name.toLowerCase();
        return (
          studentName.includes(lowerQuery) || className.includes(lowerQuery)
        );
      });
    } else {
      // Mock data for complete list (no query) - Use your provided data
      mockData = [
        {
          collection_id: 32,
          student_id: 5,
          payment_date: "2024-11-18",
          amount_received: "250.00",
          old_balance: "600.00",
          new_balance: "350.00",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-11-18T20:36:25.911Z",
          received_by: 26,
          comment: null,
          student_name: "Richmond Adasu ",
          staff_name: "admin admin",
          class_name: "Class 3",
        },
        {
          collection_id: 31,
          student_id: 4,
          payment_date: "2024-11-06",
          amount_received: "100.00",
          old_balance: "0.00",
          new_balance: "-100.00",
          fee_type: null,
          payment_mode: "Momo",
          status: "active",
          created_at: "2024-11-06T15:14:58.426Z",
          received_by: 26,
          comment: null,
          student_name: "Patience  Enyaah ",
          staff_name: "admin admin",
          class_name: "Completed",
        },
        {
          collection_id: 30,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "8.50",
          old_balance: "880.00",
          new_balance: "871.50",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-10-10T02:50:52.786Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 29,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "7.00",
          old_balance: "887.00",
          new_balance: "880.00",
          fee_type: null,
          payment_mode: "Cash",
          status: "active",
          created_at: "2024-10-10T02:49:04.670Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 28,
          student_id: 3,
          payment_date: "2024-10-10",
          amount_received: "10.50",
          old_balance: "897.50",
          new_balance: "887.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-10T00:14:37.436Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 27,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.50",
          old_balance: "899.00",
          new_balance: "897.50",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:55:56.647Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 25,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.50",
          old_balance: "901.00",
          new_balance: "899.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:25:14.010Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 24,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "902.00",
          new_balance: "901.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:15:29.191Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 23,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "2.00",
          old_balance: "904.00",
          new_balance: "902.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T23:13:31.926Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 22,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "905.00",
          new_balance: "904.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:25:12.925Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 21,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "2.00",
          old_balance: "907.00",
          new_balance: "905.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:21:34.792Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 20,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "1.00",
          old_balance: "908.00",
          new_balance: "907.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:11:55.743Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 19,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "19.00",
          old_balance: "927.00",
          new_balance: "908.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:08:53.451Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 18,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "32.50",
          old_balance: "960.00",
          new_balance: "927.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T21:06:16.128Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 17,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "40.00",
          old_balance: "1000.00",
          new_balance: "960.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T20:53:45.942Z",
          received_by: 26,
          comment: "this is the best comment yet",
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 16,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "420.00",
          old_balance: "1420.00",
          new_balance: "1000.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T20:06:12.977Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 15,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "60.00",
          old_balance: "1480.00",
          new_balance: "1420.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:36:41.679Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 14,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "36.50",
          old_balance: "1490.00",
          new_balance: null,
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:24:16.790Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 12,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "150.00",
          old_balance: "1640.00",
          new_balance: "-1490.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T19:05:52.823Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 11,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "125.00",
          old_balance: "1765.00",
          new_balance: "-1640.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T17:26:26.859Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 10,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "100.00",
          old_balance: "1865.00",
          new_balance: "-1765.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T08:28:31.167Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 9,
          student_id: 3,
          payment_date: "2024-10-09",
          amount_received: "300.00",
          old_balance: "2165.00",
          new_balance: "-1865.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-09T00:32:16.913Z",
          received_by: 26,
          comment: null,
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 8,
          student_id: 2,
          payment_date: "2024-10-08",
          amount_received: "50.00",
          old_balance: "50.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-10-08T22:29:03.668Z",
          received_by: 26,
          comment: null,
          student_name: "John Nyarkoh",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 7,
          student_id: 2,
          payment_date: "2024-09-17",
          amount_received: "850.00",
          old_balance: "800.00",
          new_balance: "50.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-09-17T05:46:15.338Z",
          received_by: 26,
          comment: "not needed",
          student_name: "John Nyarkoh",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 6,
          student_id: 3,
          payment_date: "2024-09-16",
          amount_received: "900.00",
          old_balance: "700.00",
          new_balance: "200.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-09-16T21:37:42.335Z",
          received_by: 26,
          comment: "not a sensible comment",
          student_name: "Matilda  Attah ",
          staff_name: "admin admin",
          class_name: "JHS 2",
        },
        {
          collection_id: 5,
          student_id: 1,
          payment_date: "2024-08-24",
          amount_received: "-50.00",
          old_balance: "0.00",
          new_balance: "-50.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-24T00:02:45.215Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 4,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "40.00",
          old_balance: "32.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:59:51.816Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 3,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "-32.00",
          old_balance: "0.00",
          new_balance: "32.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:56:33.864Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 2,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "50.00",
          old_balance: "30.00",
          new_balance: "0.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T23:48:53.982Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
        {
          collection_id: 1,
          student_id: 1,
          payment_date: "2024-08-23",
          amount_received: "50.00",
          old_balance: "80.00",
          new_balance: "30.00",
          fee_type: null,
          payment_mode: null,
          status: "active",
          created_at: "2024-08-23T22:52:06.443Z",
          received_by: 26,
          comment: null,
          student_name: "nelson1 Dorkordi",
          staff_name: "admin admin",
          class_name: "class 2b",
        },
      ]; // Add more data here as needed
    }

    return NextResponse.json(mockData, { status: 200 });
  } catch (error) {
    console.error("Error:", error); // Log the error for debugging
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
